# Generated by Django 6.0.5 on 2026-05-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('French', 'French')], max_length=20)),
                ('category', models.CharField(choices=[('History', 'History'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Literary Fiction', 'Literary Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Cookbooks/Crafts', 'Cookbooks/Crafts'), ('Science & Tech', 'Science & Tech')], max_length=50)),
                ('call_number', models.CharField(max_length=3)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('edition', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='Books.book')),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
